### ISSUE TITLE
Crashing on 1.17.1

### ISSUE THREAD

**Issue by SecretlyJealous** [Johni0702/bobby#34] opened 2021-07-09 16:42 UTC
I updated to 1.17.1 but whenever I join a server I crash with this: https://pastebin.com/RUycYW14

**Comment by RDKRACZ** [comment] 2021-07-09 16:51
Duplicate of #32 and #33.
There is no release for 1.17.1 yet.

**Comment by SecretlyJealous** [comment] 2021-07-14 12:45
Fixed by https://github.com/Johni0702/bobby/pull/37

**Closed** 2021-07-17 21:06 UTC
