### ISSUE TITLE
Bobby Crashes game after trying to join online servers

### ISSUE THREAD

**Issue by NightcoreBrianna** [Johni0702/bobby#116] opened 2022-10-23 04:32 UTC
Goes from Joining world, then saving world, then crashes my Minecraft and the Minecraft launcher does not open back up until I kill it in task manager! Gif shows it right here ------>  https://gyazo.com/2020834f3cb6d33d76195a76f8f1c2ea (After it says saving world it disappears after into a crash). 

<img width="741" alt="Capture" src="https://user-images.githubusercontent.com/15710069/197373623-42ee17db-9823-4aaf-ae61-8bb1fe49713b.PNG">

<img width="737" alt="Capture" src="https://user-images.githubusercontent.com/15710069/197373661-36f18cbb-711d-4857-94f8-b9591c06a7df.PNG">
[latest.log](https://github.com/Johni0702/bobby/files/9845769/latest.log)

Using Windows 10! 

and these are my only mods installed! (no <img width="526" alt="Capture" src="https://user-images.githubusercontent.com/15710069/197374351-920625b2-e4eb-4e7f-9cbf-19b423251394.PNG"> Shader packs  and no texture packs)

[The mod works perfectly fine in single player] But when joining servers it just crashes!

**Comment by Brancieq-Paul** [comment] 2022-10-23 11:02
I have the exact same problem, with just optifabric and optifine.

**Comment by NightcoreBrianna** [comment] 2022-10-23 15:41
I just tested it by removing optifabric and optifine and works fine but that's not good! I use them mods to be able to run my shaders! 
So Bobby cant join online servers with optifabric and optifine but Bobby can join online servers without optifabric and optifine.
Hopefully this can be fixed!

**Comment by NJDaeger** [comment] 2022-10-24 20:21
I have dug into this a little bit, and I believe if you have your framerate set to VSync, it causes it to crash. https://github.com/Johni0702/bobby/blob/master/src/main/java/de/johni0702/minecraft/bobby/mixin/MinecraftClientMixin.java#L40 this is the line I believe was causing it, and I am assuming that if it is set to VSync, maxFps is 0.

Set your FPS limit to unlimited and it works just fine.

**Comment by Johni0702** [comment] 2022-10-25 17:21
Duplicate of #105

**Closed by Johni0702** 2022-10-25 17:21 UTC
