### ISSUE TITLE
Can't increase render distance past 32

### ISSUE THREAD

**Issue by 1Lightspeed1** [Johni0702/bobby#87] opened 2022-03-22 23:09 UTC
I'm playing 1.18.2 (on MultiMC launcher), and I'm configuring the settings through the cloth config mod. I'm changing the max value in the Bobby mod to 64, but in the Sodium vid settings, when I set it past 64, apply the changes, then exit the screen and go back in, it reverts back to 32 chunks. I don't know if there's any changes I have to make or if it's me being clueless about how the mod works.

Mods I'm using:
Fabric API
Sodium
Lithium
Phosphor
Logical Zoom
Fabric Notes
Replay Mod
Cloth API
Cloth Config v6
Bobby

Please let me know if any of these mods are incompatible with Bobby.

**Comment by Johni0702** [comment] 2022-03-23 05:35
Duplicate of #76

**Closed by Johni0702** 2022-03-23 05:35 UTC
