### ISSUE TITLE
There is no "Config" option in mod menu

### ISSUE THREAD

**Issue by Mulakulu** [Johni0702/bobby#251] opened 2024-02-20 13:34 UTC
I am missing the config button in the top right corner for bobby. It is there for mods like mod menu, minecraft and zoomify. I also do not see a way to turn render distance above 32 chunks

![image](https://github.com/Johni0702/bobby/assets/22845572/c43c5621-3a08-48fc-9240-be8188737fed)

**Comment by Mulakulu** [comment] 2024-02-20 13:52
I found the config file and changed the view-distance-overwrite manually and it worked.

**Comment by Obscure2020** [comment] 2024-02-20 15:44
Did you forget to install Cloth Config API?

**Comment by Mulakulu** [comment] 2024-02-20 22:34
No. I installed the newest version of Bobby together with the newest version of all required mods, being mod menu, cloth and sodium. I also had Nvidium and all mods required for and including Zoomify on 1.20.4 on the latest stable version of Fabric. Of course fabric version of all mods. 

I don't believe I would be able to get the mod to work without Cloth Config API, right? I got the mod to work, just by messing with the config file manually.

**Comment by Mulakulu** [comment] 2024-02-20 22:35
Oh wait... I installed neoforge cloth config. My bad

**Comment by Obscure2020** [comment] 2024-02-20 22:46
Bobby will run just fine without Cloth Config properly installed. The only thing that won't function, as you found, is that the button for the config menu won't appear in the Mod Menu.

If you are able to access the config menu now, I recommend closing this issue as caused by user error, not a code bug.

**Closed** 2024-05-05 12:28 UTC
