### ISSUE TITLE
version 1.20

### ISSUE THREAD

**Issue by awentivzera** [Johni0702/bobby#191] opened 2023-07-10 18:01 UTC
I would like to ask for the transfer of Bobby mod to version 1.20, since there is not much difference between 1.20 and 1.20.1, most people are now playing on 1.20, because more mods have been released on it than on 1.20.1, and the same build with bobby mod on 1.20.1 does not start in the build of mods for version 1.20, please transfer the mod to version 1.20

**Comment by stephanrenggli** [comment] 2023-07-18 22:50
You can make this compatible with 1.20 yourself:
1. Download the mod
2. Open the .jar file with 7-zip or a similar tool
3. Open the file `fabric.mod.json`
4. Edit the line `"minecraft": "~1.20.1"` to `"minecraft": "~1.20"`. You can find this under `"depends"`.

**Comment by Johni0702** [comment] 2023-08-13 10:18
Duplicate of #185

**Closed by Johni0702** 2023-08-13 10:18 UTC
