### ISSUE TITLE
Bobby dousnt load more than 32 chuncks

### ISSUE THREAD

**Issue by oHartog** [Johni0702/bobby#245] opened 2024-02-03 17:58 UTC
Bobby won't load more than 32 chunks with the most recent version. If I set it to 128 for example it will only show 32.

**Comment by Obscure2020** [comment] 2024-02-06 14:50
Did you set the render distance maximum to a higher number than 32 in Bobby's config menu _**AND**_ then turn the render distance up in Video Settings? You have to do both, in that order.

**Comment by MeYouGitHub** [comment] 2024-02-14 03:53
I am getting the excact same error

**Comment by Johni0702** [comment] 2024-05-05 11:03
Duplicate of #243

**Closed by Johni0702** 2024-05-05 11:03 UTC
