### ISSUE TITLE
only 32 chunks rendering but the clouds go as far as the number I set it to. I'm on singleplayer.

### ISSUE THREAD

**Issue by bryanfc3** [Johni0702/bobby#266] opened 2024-04-16 19:28 UTC
![image_2024-04-16_152843045](https://github.com/Johni0702/bobby/assets/167246391/80c3d6bb-a867-403d-85db-84e481b2b5e9)

**Comment by Johni0702** [comment] 2024-05-05 12:48
Duplicate of #253

**Closed by Johni0702** 2024-05-05 12:48 UTC
