### ISSUE TITLE
Singleplayer 32 chunk issue

### ISSUE THREAD

**Issue by HoneyRyu12** [Johni0702/bobby#256] opened 2024-03-01 09:26 UTC
When I set render distance to 64, only 32 chunks loads. how to make 64 chunks load?
Mods
appleskin
bobby
c2me
dynamic fps
entity culling
fabric language kotlin
ferritecore
freecam
immediatelyfast
indium
iris shaders
krypton
lambdynamiclights
lithium
malilib
minecraftcapes
mod menu
modern fix
nofog
nvidium
reese's sodium option
replaymod
simple hud enchanted
sodium
sodium extra
wavey capes
yetanotherconfiglib
zoomify
advancementinfo
clothconfig
forge config api port
inventory sorting
litematica
starlight
tweakeroo

**Comment by mcnuggetsx20** [comment] 2024-04-03 20:51
I have the same issue. On singleplayer setting render distance above 32 has no effect on the actual number of chunks being loaded.

**Comment by vertexgamer** [comment] 2024-04-07 10:28
Same ISSUE: 1.20.4 with latest sodium 0.5.8
Chunks above 32 will cull even if already generated, only clouds seems to work as intended.
I even tried renaming the world folder to "bobby-fallback" but no success.

**Comment by berat615141** [comment] 2024-04-11 06:04
Same 1.20.1  anyone has opinion? What to do?

**Comment by Arester11** [comment] 2024-04-12 02:51
Same problems: 1.20.4 with Bobby v5.1.0 and sodium v0.5.8
Going beyond 32 chunks doesn't generate new terrain but clouds work

**Comment by Johni0702** [comment] 2024-05-05 12:45
Duplicate of #253

**Closed by Johni0702** 2024-05-05 12:45 UTC
