### ISSUE TITLE
Bobby needs an update

### ISSUE THREAD

**Issue by Smilerr** [Johni0702/bobby#202] opened 2023-08-10 18:26 UTC
Bobby needs to update to work with the newest version of Sodium.

To reproduce this, have Bobby 5.0.0 installed, and the newest version of Sodium. It will crash your game anytime you join a world. This includes servers, single player worlds, and realms.

I sent an issue report to Sodium, and they said this was the problem.

Hope you see this.

**Comment by iso2013** [comment] 2023-08-11 00:31
This is a duplicate of #197 , which has a lot of activity & work done already.

**Comment by Johni0702** [comment] 2023-08-13 10:27
Duplicate of #197

**Closed by Johni0702** 2023-08-13 10:27 UTC
