### ISSUE TITLE
Chunks near the player are being unloaded in a weird pattern only to load again.

### ISSUE THREAD

**Issue by RDKRACZ** [Johni0702/bobby#36] opened 2021-07-11 13:11 UTC
Bobby 2.0.2
MC 1.17
Sodium 0.3.0+build.503
Video - https://streamtape.com/v/dqA9evlGR1CQro/simplescreenrecorder-2021-07-11_15.06.44.mkv

**Comment by SecretlyJealous** [comment] 2021-07-14 12:59
I've got a similar problem where loading chunks outside of a servers view distance causes some weird flashing, it's as if it's being unloaded and loaded again: https://gfycat.com/groundedfearfulboilweevil

**Comment by Johni0702** [comment] 2021-07-14 14:42
Duplicate of #26

**Closed by Johni0702** 2021-07-14 14:42 UTC

**Comment by Johni0702** [comment] 2021-07-18 07:57
Not actually a duplicate (that bug appears to be fixed with Sodium 0.3.0) but just an incompatible change in Sodium 0.3.0 compared to when I added support for it to Bobby.
Sodium 0.3.0 (proper, not a snapshot) should be compatible with Bobby as of version 2.0.4 (https://github.com/Johni0702/bobby/commit/9fb17d37fbe3658b384a043f11cd9973c6f17487).
