### ISSUE TITLE
is it possible to update to 1.21 myself and rebuild it ? 

### ISSUE THREAD

**Issue by Mimibienv** [Johni0702/bobby#286] opened 2024-06-16 12:50 UTC
is it possible to update to 1.21 myself and rebuild it ?

**Comment by ItzDerock** [comment] 2024-06-16 15:30
Yeah, checkout PR #285 and run `./gradlew build`. Jar will be outputted to `./build/libs/bobby-5.2.0+mc1.21.jar` 

I've built a version and attached it: [bobby.zip](https://github.com/user-attachments/files/15858852/bobby.zip)

**Comment by ThisCatLikesCrypto** [comment] 2024-06-16 18:29
i'm compiling it now, if it's successful i'll upload the jar

**Comment by ThisCatLikesCrypto** [comment] 2024-06-16 18:31
> I've built a version and attached it: [bobby.zip](https://github.com/user-attachments/files/15858852/bobby.zip)

ty for the build, i tried myself but it didn't work

**Comment by Johni0702** [comment] 2024-06-17 19:48
Duplicate of #284

**Closed by Johni0702** 2024-06-17 19:48 UTC
