### ISSUE TITLE
ArithmeticException: divide by zero

### ISSUE THREAD

**Issue by MrMiumo** [Johni0702/bobby#160] opened 2023-05-09 16:24 UTC
When using Optifine + Optifabric + Fabric in the latest versions, I can't join servers without crashing the game with the following error. Any idea of from where it comes ?

```log
[18:13:07] [Render thread/ERROR]: Unreported exception thrown!
java.lang.ArithmeticException: / by zero
	at net.minecraft.class_310.handler$zzm000$bobby$bobbyUpdate(class_310.java:3018) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1177) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:801) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:237) ~[fabric-loader-0.14.19-1.19.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:462) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.19.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.19.jar:?]
```

**Comment by Johni0702** [comment] 2023-05-11 18:22
Duplicate of #105

**Closed by Johni0702** 2023-05-11 18:22 UTC
