### ISSUE TITLE
Chunk server to local world.

### ISSUE THREAD

**Issue by Alkogolik1604** [Johni0702/bobby#146] opened 2023-03-15 22:41 UTC
Is there any way to convert data saved by the Bobby mod for a server into a world? I've copied my .bobby folder of the world and am trying to recover the world of a deleted SMP. So far I've tried replacing the files in the region folder of a new world with files of various overworld folders from folders in the SMP's .bobby world folder but that doesn't seem to do anything. Judging by how long it takes to rejoin the world each time after this, I'm fairly sure these chunks are being re-generated by the world seed or maybe just ignored, making no impact on the world itself.

**Comment by Johni0702** [comment] 2023-03-19 20:14
Duplicate of #89

**Closed by Johni0702** 2023-03-19 20:14 UTC
