### ISSUE TITLE
Player falls into the void after teleporting big distance

### ISSUE THREAD

**Issue by DerpNerb** [Johni0702/bobby#46] opened 2021-08-28 10:03 UTC
I'm playing on Wynncraft with this mod, in combination with Sodium. It works great, the only thing is that when I get teleported a big distance I often fall into the void because the chunks near the player don't load. Sometimes I don't fall down, but just hover in place.
Reloading all chunks doesn't work, I have to relog in order to fix this.

This is what it looks like:
![2021-08-28_11 56 41](https://user-images.githubusercontent.com/39121384/131214298-f635f866-e284-4457-83a8-be97bd7437e2.png)

Any ideas as to how to fix this? It looks like the server isn't fast enough in sending the chunks, but in vanilla this works just fine!

**Comment by Johni0702** [comment] 2021-08-28 11:16
Huh, I've never had that happen to me. How reliably is it / can you put "often" into numbers?
How did you teleport there? Seaskipper or Nexus? If it's the latter, did you stay in the Nexus for more than a minutes (or whatever you set the unload delay to if you changed it)?
Please check if this happens with all other mods removed as well. And state your exact version of Bobby (and the versions of other mods required to reproduce it if any).

**Comment by DerpNerb** [comment] 2021-08-29 14:34
Right so it turns out it is a compatibility issue, mods that read the world data makes the game freak out or something is my guess.

Mods that caused this:
- Entity Culling
- Cull leaves
- Fast chests
- Xaero's Mini map
- Xaero's world map

I now play without those mods. I do hope you manage to fix this, as it's a bobby issue. As soon as I disable bobby in the mod menu, it works just fine :/

**Comment by Johni0702** [comment] 2021-08-29 14:46
I asked for five different things, you answered one of them and only half of it.

Here's my message again with the thing you've already answered removed:
> Huh, I've never had that happen to me. How reliably is it / can you put "often" into numbers?
How did you teleport there? Seaskipper or Nexus? If it's the latter, did you stay in the Nexus for more than a minutes (or whatever you set the unload delay to if you changed it)?
~~Please check if this happens with all other mods removed as well.~~ And state your exact version of Bobby (and the versions of other mods required to reproduce it if any).

Also, now that I know that it's a mod compatibility issue, please attach the `latest.log` file the next time it happens, there may very well be an error printed in there which caused those chunks to not load (and it would also list the versions of all mods).

> it's a bobby issue. As soon as I disable bobby in the mod menu, it works just fine

That's not how causality works. It may very well just be that, e.g. Xaero's Minimap doesn't deal well with chunks outside the server view distance or something. Xaero's mods are All Rights Reserved, so I'm not even allowed to check, and you'd have to ask their author if the log indicates that it is an issue with those.

**Comment by DerpNerb** [comment] 2021-08-29 16:23
Sorry it was more of an update to my own post instead of a response to you.

Here are the answers to your questions:
1. Actually the probability is 100% with the mods installed if you teleport to outside the loaded chunks (so more than 32 chunks in my case). Only difference is that sometimes I fall and sometimes I keep lagging into place.
2. I used seaskipper, but this happens with a lot of teleports. Like playing quests is basically impossible because you get teleported quite often and fall to your death.
3. I’m using the latest version of Bobby for Minecraft 1.17.1. Also the latest version for the other mods.

I’ll see if I can add the log when I’m back at my pc

**Comment by RDKRACZ** [comment] 2021-08-30 11:04
Happened to me just now. This is spammed in the log. I'm not using any of the mods @DerpNerb uses besides Sodium (0.3.2) and Sodium Extra. 
```
[12:56:57] [Render thread/WARN]: Ignoring chunk since it's not in the view range: 4102, 4088
[12:56:57] [Render thread/FATAL]: Error executing task on Client
java.lang.NullPointerException: null
[12:56:57] [Render thread/WARN]: Ignoring chunk since it's not in the view range: 4102, 4098
[12:56:57] [Render thread/FATAL]: Error executing task on Client
java.lang.NullPointerException: null
[12:56:57] [Render thread/WARN]: Ignoring chunk since it's not in the view range: 4101, 4099
[12:56:57] [Render thread/FATAL]: Error executing task on Client
java.lang.NullPointerException: null
[12:56:57] [Render thread/WARN]: Ignoring chunk since it's not in the view range: 4090, 4099
[12:56:57] [Render thread/FATAL]: Error executing task on Client
java.lang.NullPointerException: null
[12:56:57] [Render thread/WARN]: Ignoring chunk since it's not in the view range: 4090, 4087
[12:56:57] [Render thread/FATAL]: Error executing task on Client
java.lang.NullPointerException: null
[12:56:57] [Render thread/WARN]: Ignoring chunk since it's not in the view range: 4102, 4087
[12:56:57] [Render thread/FATAL]: Error executing task on Client
java.lang.NullPointerException: null
[12:56:57] [Render thread/WARN]: Ignoring chunk since it's not in the view range: 4102, 4099
```

![2021-08-30_12 57 09](https://user-images.githubusercontent.com/43277609/131329837-f7343f26-017a-4dc6-9dec-a91c81e9c081.png)

**Comment by Johni0702** [comment] 2021-12-14 18:19
For the "Ignoring chunk since it's not in the view range" case, I'm inclined to put that on the server because Bobby doesn't mess with any of that and only injects into code which executes at a later point, so it realistically couldn't directly cause it.

I'm closing the main issue due to lack of information ("latest" is not a version, idk what you thought was latest at the time; and I've yet to see a full log) and by extension ability to reproduce.
If this happens again, please remove any mods not required to reproduce it, open a new issue, clearly state their exact and unambiguous versions and include the full log.

**Closed by Johni0702** 2021-12-14 18:19 UTC
