### ISSUE TITLE
bobby or optifine(optifabric) crashing the game

### ISSUE THREAD

**Issue by pipipupu-ui** [Johni0702/bobby#103] opened 2022-07-09 14:34 UTC
Until optifine appeared, I played with the Sodium mod on 1.19 and everything worked fine, but after its release, I tried to enter the network game on the server, but the connection did not go through, "world save" appeared and minecraft crashed. After removing Bobby, minecraft worked fine.

**Comment by Johni0702** [comment] 2022-07-18 07:58
Please attach the crash log.
Also, if this is similar to #105, then try removing Optifine and/or changing your Max Framerate setting. Based on the reports in that issue, I'm guessing Optifine sets it to an invalid value.

**Comment by drathmorgh** [comment] 2022-08-03 01:36
I can confirm that enabling Vsync crashes the game!

**Comment by Johni0702** [comment] 2022-08-03 05:21
Duplicate of #105

**Closed by Johni0702** 2022-08-03 05:21 UTC
