### ISSUE TITLE
1.20?

### ISSUE THREAD

**Issue by JSOMaverick** [Johni0702/bobby#175] opened 2023-06-20 11:31 UTC
I saw the mod has been updated to 1.20.1 but 1.20 skipped? Is there a reason for this or a way to get it working with 1.20? 

Thank you

**Comment by Johni0702** [comment] 2023-06-20 16:32
Duplicate of #168

**Closed by Johni0702** 2023-06-20 16:32 UTC

**Comment by Johni0702** [comment] 2023-06-20 16:33
Duplicate of #171
