### ISSUE TITLE
bobby cause VERY BIG lag spikes when i move between chunks.

### ISSUE THREAD

**Issue by snek100** [Johni0702/bobby#42] opened 2021-08-06 17:56 UTC
if i disable bobby, the lag spikes go away. but if i enable bobby, there are big lag spikes (fps drops) whenever i move through a chunk border.
i tried to upload a screenshot, but it doesnt upload :(

**Comment by Johni0702** [comment] 2021-08-07 11:14
I'll need more than that. Mods, versions, hardware, etc.
Cannot reproduce.

**Comment by Arknia08** [comment] 2021-08-28 16:04
I've had the same problem, adding starlight seemed to have mostly fixed it, substantially increasing minimum fps . But as you know, starlight doesn't play well with bobby.

I'm running minecraft 1.17.1 on java 16
PC specs:
Intel i7 8700K @5GHz
32GB RAM @3200MHz CL18 (4GB allocated to MC)
GTX 1080Ti @2025MHz

Here is a list of the mods I'm using
![Untitled](https://user-images.githubusercontent.com/89664276/131222778-539b688a-3790-42d3-b2b7-761d1139f679.png)

Without Starlight:
![2021-08-28_17 25 26](https://user-images.githubusercontent.com/89664276/131222935-3fd37123-ab0c-48e2-adb9-49558d1b62fb.png)

With Starlight:
![2021-08-28_17 58 00](https://user-images.githubusercontent.com/89664276/131223679-dfeba4c7-f062-47d3-9d72-b53d8e5dc7ae.png)

Another thing that helped was installing my MC client and subsequently bobby's files on a ram disk. (About doubling minimum framerates)

So my guess is is that it is a combination of high access latency and vanilla's super inefficient chunk building system not playing nicely on certain hardware/mod configurations.
Hope this helps :)

**Comment by NamiUni** [comment] 2021-09-04 09:33
I think it's a vanilla bug.
https://bugs.mojang.com/browse/MC-162253

The reason you don't get this problem after installing StarLight is because StarLight fixes this problem.

**Comment by Arknia08** [comment] 2021-09-05 16:29
I don't think it is, because I don't have this issue in vanilla at all.

**Comment by NamiUni** [comment] 2021-09-11 12:00
You need to set the server view distance and client view distance to the same value as the view distance set in bobby and test it.

**Comment by Johni0702** [comment] 2021-12-14 18:06
Closing as likely vanilla bug which is just more noticeable with Bobby because it loads more chunks.
Also, Bobby now works with Starlight, so there's a good fix for it.

**Closed by Johni0702** 2021-12-14 18:06 UTC
