### ISSUE TITLE
1.18.2 Chunk Slider is limited to 32

### ISSUE THREAD

**Issue by Igetsisss** [Johni0702/bobby#86] opened 2022-03-21 15:33 UTC
I did try to use the config mod to set the slider to more than 32 it did work but after I exited video setting it immediately set it back to 32

**Comment by Johni0702** [comment] 2022-03-21 15:37
Known issue, you need to restart the game for it to fully take effect atm.

**Comment by Johni0702** [comment] 2022-03-21 15:37
Duplicate of #76

**Closed by Johni0702** 2022-03-21 15:37 UTC
