### ISSUE TITLE
You cant configure bobby mod

### ISSUE THREAD

**Issue by Invoren** [Johni0702/bobby#231] opened 2024-01-12 15:04 UTC
Ive been trying to configure it with mod menu but the option just does not show up anyone know a fix? (I dont have any map mods and a i have sodium)

**Comment by antoneser1** [comment] 2024-01-13 13:39
YES! You have to install Cloth Config API ( https://modrinth.com/mod/cloth-config/version/11.1.118+fabric )

**Comment by Grizzly096** [comment] 2024-01-14 09:40
If you already have Cloth Config API installed and it still doesnt work then make sure its for fabric because that was my problem

**Comment by eSonOfAnder** [comment] 2024-01-23 23:33
I suspect OP is having the same issue I was, and it's not obvious if you've never used the mod before. You have to first change Bobby's config to allow render distance higher than 32 chunks, and THEN the video settings screen will allow you to raise the render distance above 32. If you have Mod Menu and Cloth Config installed, you can go into Mods from the main game menu, and click on the icon of the mod to go into its config to make the update there. This should probably be mentioned somewhere on the main page for the mod on Modrinth that the default Bobby config doesn't change anything, and you have to go in and update it before you will see any changes.

**Comment by Johni0702** [comment] 2024-01-31 14:09
Duplicate of #227

**Closed by Johni0702** 2024-01-31 14:09 UTC
