### ISSUE TITLE
No 1.20 version

### ISSUE THREAD

**Issue by JawBroke** [Johni0702/bobby#177] opened 2023-06-21 16:16 UTC
The server I am playing on is currently on 1.20 so I can't play on 1.20.1 yet, but fabric does not let you use the 1.20.1 version of the mod.. I can't find a 1.20 version of the mod anywhere

**Comment by Johni0702** [comment] 2023-06-21 19:41
Duplicate of #176

**Closed by Johni0702** 2023-06-21 19:41 UTC
