### ISSUE TITLE
" | " in world name causes Bobby to not function

### ISSUE THREAD

**Issue by justifierna** [Johni0702/bobby#244] opened 2024-02-02 23:55 UTC
So here's an interesting one: If you have the character " | " in your world names, Bobby will error out

Scenario 1:
-  not load past 100%

or

Scenario 2:
- crash if I force it to load by deleting the Bobby Profile, loading the world, setting up Bobby then entering another dimension

It's interesting because it works as long as it's not on that specific world

The following is the errors I get

SCENARIO 1:

> **Caused by: java.nio.file.InvalidPathException: Illegal char <|> at index 19: Hardcore Minecraft | 02/08/2023**

```
[17:36:32] [Server thread/INFO]: Justifierna joined the game
[17:36:33] [Render thread/ERROR]: Error executing task on Client
net.minecraft.class_148: Main thread packet handler
	at net.minecraft.class_2600.method_11072(class_2600.java:33) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1283) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:888) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:265) ~[fabric-loader-0.15.6-1.20.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.6.jar:?]
**Caused by: java.nio.file.InvalidPathException: Illegal char <|> at index 19: Hardcore Minecraft | 02/08/2023**
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182) ~[?:?]
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153) ~[?:?]
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77) ~[?:?]
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:92) ~[?:?]
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:232) ~[?:?]
	at java.nio.file.Path.resolve(Path.java:515) ~[?:?]
	at de.johni0702.minecraft.bobby.FakeChunkManager.<init>(FakeChunkManager.java:99) ~[bobby-5.1.0+mc1.20.4.jar:?]
	at net.minecraft.class_631.handler$zzj000$bobby$bobbyInit(class_631.java:1051) ~[client-intermediary.jar:?]
	at net.minecraft.class_631.<init>(class_631.java:42) ~[client-intermediary.jar:?]
	at net.minecraft.class_638.<init>(class_638.java:173) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_11120(class_634.java:413) ~[client-intermediary.jar:?]
	at net.minecraft.class_2678.method_11567(class_2678.java:57) ~[client-intermediary.jar:?]
	at net.minecraft.class_2678.method_11054(class_2678.java:14) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:24) ~[client-intermediary.jar:?]
	... 10 more
```

SCENARIO 2

> **Caused by: java.nio.file.InvalidPathException: Illegal char <|> at index 19: Hardcore Minecraft | 02/08/2023**

```
...
[17:39:36] [Server thread/INFO]: Justifierna joined the game
[17:39:36] [Render thread/INFO]: Started 10 worker threads
[17:39:37] [Render thread/INFO]: Loaded 783 advancements
[17:39:40] [Server thread/INFO]: Saving and pausing game...
[17:39:40] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Hardcore Minecraft | 02/08/2023]'/minecraft:overworld
[17:39:40] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Hardcore Minecraft | 02/08/2023]'/minecraft:the_end
[17:39:40] [Server thread/INFO]: Saving chunks for level 'ServerLevel[Hardcore Minecraft | 02/08/2023]'/minecraft:the_nether
[17:40:18] [Render thread/INFO]: Stopping worker threads
[17:40:18] [Render thread/INFO]: Started 10 worker threads
[17:40:18] [Render thread/INFO]: Flushed changes to Minecraft configuration
[17:40:21] [Server thread/INFO]: Changing view distance to 32, from 12
[17:40:22] [Server thread/WARN]: UUID of added entity already exists: class_1452['Pig'/677, l='ServerLevel[Hardcore Minecraft | 02/08/2023]', x=-177.25, y=73.00, z=86.80]
[17:40:22] [Server thread/WARN]: UUID of added entity already exists: class_1493['Wolf'/707, l='ServerLevel[Hardcore Minecraft | 02/08/2023]', x=-37.78, y=70.00, z=-182.22]
[17:40:34] [Render thread/ERROR]: Error executing task on Client
net.minecraft.class_148: Main thread packet handler
	at net.minecraft.class_2600.method_11072(class_2600.java:33) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1283) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:888) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:265) ~[fabric-loader-0.15.6-1.20.4.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.6.jar:?]
**Caused by: java.nio.file.InvalidPathException: Illegal char <|> at index 19: Hardcore Minecraft | 02/08/2023**
	at sun.nio.fs.WindowsPathParser.normalize(WindowsPathParser.java:182) ~[?:?]
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:153) ~[?:?]
	at sun.nio.fs.WindowsPathParser.parse(WindowsPathParser.java:77) ~[?:?]
	at sun.nio.fs.WindowsPath.parse(WindowsPath.java:92) ~[?:?]
	at sun.nio.fs.WindowsFileSystem.getPath(WindowsFileSystem.java:232) ~[?:?]
	at java.nio.file.Path.resolve(Path.java:515) ~[?:?]
	at de.johni0702.minecraft.bobby.FakeChunkManager.<init>(FakeChunkManager.java:99) ~[bobby-5.1.0+mc1.20.4.jar:?]
	at net.minecraft.class_631.handler$zzj000$bobby$bobbyInit(class_631.java:1051) ~[client-intermediary.jar:?]
	at net.minecraft.class_631.<init>(class_631.java:42) ~[client-intermediary.jar:?]
	at net.minecraft.class_638.<init>(class_638.java:173) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_11117(class_634.java:1099) ~[client-intermediary.jar:?]
	at net.minecraft.class_2724.method_11782(class_2724.java:31) ~[client-intermediary.jar:?]
	at net.minecraft.class_2724.method_11054(class_2724.java:7) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:24) ~[client-intermediary.jar:?]
	... 10 more
```

**Comment by EmilieSong** [comment] 2024-02-09 04:28
i encountered the same issue. 

``
net.minecraft.class_148: Main thread packet handler
	at net.minecraft.class_2600.method_11072(class_2600.java:33) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_18859(class_1255.java:156) ~[client-intermediary.jar:?]
	at net.minecraft.class_4093.method_18859(class_4093.java:23) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_16075(class_1255.java:130) ~[client-intermediary.jar:?]
	at net.minecraft.class_1255.method_5383(class_1255.java:115) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1283) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:888) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:265) ~[1.20.4-0.15.6.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:470) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.15.6.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.15.6.jar:?]
Caused by: java.nio.file.InvalidPathException: Illegal char <:> at index 23: Emilies personal world :D
	at sun.nio.fs.WindowsPathParser.normalize(Unknown Source) ~[?:?]
	at sun.nio.fs.WindowsPathParser.parse(Unknown Source) ~[?:?]
	at sun.nio.fs.WindowsPathParser.parse(Unknown Source) ~[?:?]
	at sun.nio.fs.WindowsPath.parse(Unknown Source) ~[?:?]
	at sun.nio.fs.WindowsFileSystem.getPath(Unknown Source) ~[?:?]
	at java.nio.file.Path.resolve(Unknown Source) ~[?:?]
	at de.johni0702.minecraft.bobby.FakeChunkManager.<init>(FakeChunkManager.java:99) ~[bobby-5.1.0+mc1.20.4.jar:?]
	at net.minecraft.class_631.handler$zfg000$bobby$bobbyInit(class_631.java:1051) ~[client-intermediary.jar:?]
	at net.minecraft.class_631.<init>(class_631.java:42) ~[client-intermediary.jar:?]
	at net.minecraft.class_638.<init>(class_638.java:173) ~[client-intermediary.jar:?]
	at net.minecraft.class_634.method_11120(class_634.java:413) ~[client-intermediary.jar:?]
	at net.minecraft.class_2678.method_11567(class_2678.java:57) ~[client-intermediary.jar:?]
	at net.minecraft.class_2678.method_11054(class_2678.java:14) ~[client-intermediary.jar:?]
	at net.minecraft.class_2600.method_11072(class_2600.java:24) ~[client-intermediary.jar:?]
	... 10 more
[17:24:53] [Render thread/ERROR]: Error executing task on Client

``

**Comment by Johni0702** [comment] 2024-05-05 13:41
Duplicate of #67

**Closed by Johni0702** 2024-05-05 13:41 UTC
