### ISSUE TITLE
Add support for 1.18.2

### ISSUE THREAD

**Issue by SecretlyJealous** [Johni0702/bobby#80] opened 2022-03-03 14:07 UTC
1.18.2 has been released in case you didn't know, would be nice if you could make the mod work for it whenever you get the time

**Comment by giorov** [comment] 2022-03-05 21:09
I get a crash, not just with bobby, but some other out of date mods too. Bobby is definitely the one I care about the most though. I run Sodium and Iris, FerriteCore, Starlight, Cloth, Lithium, Lambda better glass and grass, and several others that all worked fine up to 1.18.1.

java.lang.RuntimeException: Could not execute entrypoint stage 'main' due to errors, provided by 'confabricate'!
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:452)
	at net.minecraft.client.main.Main.main(Main.java:197)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:568)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:416)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:77)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
Caused by: java.lang.RuntimeException: Mixin transformation of net.minecraft.class_3486 failed
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:252)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.tryLoadClass(KnotClassDelegate.java:150)
	at net.fabricmc.loader.impl.launch.knot.KnotClassLoader.loadClass(KnotClassLoader.java:155)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:520)
	at ca.stellardrift.confabricate.mixin.FluidTagsAccessor.getRequiredTags(FluidTagsAccessor.java)
	at ca.stellardrift.confabricate.typeserializers.MinecraftSerializers.populate(MinecraftSerializers.java:245)
	at ca.stellardrift.confabricate.typeserializers.MinecraftSerializers.collection(MinecraftSerializers.java:192)
	at ca.stellardrift.confabricate.Confabricate.onInitialize(Confabricate.java:97)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:47)
	... 11 more
Caused by: org.spongepowered.asm.mixin.transformer.throwables.MixinTransformerError: An unexpected critical error was encountered
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:392)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClass(MixinTransformer.java:234)
	at org.spongepowered.asm.mixin.transformer.MixinTransformer.transformClassBytes(MixinTransformer.java:202)
	at net.fabricmc.loader.impl.launch.knot.KnotClassDelegate.getPostMixinClassByteArray(KnotClassDelegate.java:247)
	... 19 more
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [confabricate.accessor.mixins.json:FluidTagsAccessor] from phase [DEFAULT] in config [confabricate.accessor.mixins.json] from mod [confabricate] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:638)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:589)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379)
	... 22 more
Caused by: org.spongepowered.asm.mixin.gen.throwables.InvalidAccessorException: No candidates were found matching field_23680:Lnet/minecraft/class_5120; in net/minecraft/class_3486 for confabricate.accessor.mixins.json:FluidTagsAccessor->@Accessor[FIELD_GETTER]::getRequiredTags()Lnet/minecraft/class_5120; [INJECT Applicator Phase -> confabricate.accessor.mixins.json:FluidTagsAccessor -> Apply Accessors ->  -> Locate -> confabricate.accessor.mixins.json:FluidTagsAccessor->@Accessor[FIELD_GETTER]::getRequiredTags()Lnet/minecraft/class_5120;]
	at org.spongepowered.asm.mixin.gen.AccessorInfo.findTarget(AccessorInfo.java:518)
	at org.spongepowered.asm.mixin.gen.AccessorInfo.findTargetField(AccessorInfo.java:501)
	at org.spongepowered.asm.mixin.gen.AccessorInfo.locate(AccessorInfo.java:475)
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.generateAccessors(MixinTargetContext.java:1412)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyAccessors(MixinApplicatorStandard.java:1061)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.applyMixin(MixinApplicatorStandard.java:398)
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:325)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:421)
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:403)
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363)
	... 22 more


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.lambda$invoke0$0(EntrypointUtils.java:51)
	at net.fabricmc.loader.impl.util.ExceptionUtil.gatherExceptions(ExceptionUtil.java:33)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke0(EntrypointUtils.java:49)
	at net.fabricmc.loader.impl.entrypoint.EntrypointUtils.invoke(EntrypointUtils.java:35)
	at net.fabricmc.loader.impl.game.minecraft.Hooks.startClient(Hooks.java:52)
	at net.minecraft.class_310.<init>(class_310.java:452)

**Comment by Johni0702** [comment] 2022-03-06 07:17
Seems like an update of https://github.com/zml2008/confabricate is required. There's a "Begin update for 1.18" commit from four days ago, so I'm guessing it's WIP and we'll just have to wait until it's released.

**Comment by giorov** [comment] 2022-03-06 09:31
Ah yes I think a lot of the mods that don't work have this dependancy in fact. Thanks for the update on that.

**Comment by giorov** [comment] 2022-03-11 17:13
[NightEule5](https://github.com/NightEule5) commented https://github.com/LambdAurora/LambdaBetterGrass/issues/45#issuecomment-1061321650 "The mixin for net.minecraft.class_3304 which maps to net.minecraft.resource.ReloadableResourceManagerImpl is failing. The method method_14475, which maps to addPack in 1.18.1, is missing from 1.18.2's mappings. It must've been removed"

**Comment by wafflecoffee** [comment] 2022-03-11 20:44
Bobby works fine on 1.18.2 if you drop in a newer version of Confabricate.
https://repo.stellardrift.ca/repository/snapshots/ca/stellardrift/confabricate/3.0.0-SNAPSHOT/confabricate-3.0.0-20220303.200452-4.jar

> Seems like an update of [zml2008/confabricate](https://github.com/zml2008/confabricate) is required. There's a "Begin update for 1.18" commit from four days ago, so I'm guessing it's WIP and we'll just have to wait until it's released.

You can still use it from the snapshots repository; specifically `3.0.0-SNAPSHOT`. See the [usage instructions](https://github.com/zml2008/confabricate#how-to-use) for the snapshots repository.

**Comment by forshale** [comment] 2022-03-11 21:05
> 

See, what's weird to me is that with this the game does launch and I can get into the server I play on.  But, after playing in the world for a few seconds, it just crashes.  I took out all the other mods I use and only had the bare minimum, but got this: using bobby 3.1
[crash-2022-03-11_13.01.01-client.txt](https://github.com/Johni0702/bobby/files/8235731/crash-2022-03-11_13.01.01-client.txt)

my mods are : bobby 3.1.0, cloth 6.2.57, confabricate 3.0.0 (snapshot you sent), fabric api 0.47.10, mod menu 3.1.0, and sodium fabric 0.4.1+build15.  Are there conflicting mods? Or is it an issue with confabricate alone?

**Comment by forshale** [comment] 2022-03-11 21:06
> Bobby works fine on 1.18.2 if you drop in a newer version of Confabricate. https://repo.stellardrift.ca/repository/snapshots/ca/stellardrift/confabricate/3.0.0-SNAPSHOT/confabricate-3.0.0-20220303.200452-4.jar
> 
> > Seems like an update of [zml2008/confabricate](https://github.com/zml2008/confabricate) is required. There's a "Begin update for 1.18" commit from four days ago, so I'm guessing it's WIP and we'll just have to wait until it's released.
> 
> You can still use it from the snapshots repository; specifically `3.0.0-SNAPSHOT`. See the [usage instructions](https://github.com/zml2008/confabricate#how-to-use) for the snapshots repository.

See, what's weird to me is that with this the game does launch and I can get into the server I play on. But, after playing in the world for a few seconds, it just crashes. I took out all the other mods I use and only had the bare minimum, but got this: using bobby 3.1
[crash-2022-03-11_13.01.01-client.txt](https://github.com/Johni0702/bobby/files/8235731/crash-2022-03-11_13.01.01-client.txt)

my mods are : bobby 3.1.0, cloth 6.2.57, confabricate 3.0.0 (snapshot you sent), fabric api 0.47.10, mod menu 3.1.0, and sodium fabric 0.4.1+build15. Are there conflicting mods? Or is it an issue with confabricate alone?

**Comment by wafflecoffee** [comment] 2022-03-11 21:16
That's... weird. It works for me, but maybe Bobby does need some additional changes. Not sure.

**Comment by forshale** [comment] 2022-03-11 21:21
Yeah I just tested a whole different array of mods, and ran confabricate alone. It seems to be an issue with bobby itself running with the new confabricate, do you think I should create a new issue? Or keep to this thread?

> That's... weird. It works for me, but maybe Bobby does need some additional changes. Not sure.

**Comment by Johni0702** [comment] 2022-03-12 08:30
Turns out Confabricate doesn't do all that much which Bobby depends on. So I've replace the strong dependency with a soft one, falling back to using Configurate (the Minecraft independent lib behind Confabricate) directly (https://github.com/Johni0702/bobby/commit/77d0035d50a75f976a9dd6b52ad02d3241e777c8).

And then a small amount of extra work was needed to make Bobby itself work with 1.18.2 (https://github.com/Johni0702/bobby/commit/b1cc5d86d97b9d761f4b0013837ae946c4c02974).

Released as Bobby 3.1.1 to GitHub, Modrinth and (once approved) CurseForge.

**Closed by Johni0702** 2022-03-12 08:30 UTC

**Comment by forshale** [comment] 2022-03-12 09:06
Wonderful news! Thanks for you hard work on this mod, and I can finally enjoy 1.18.2 now! Yay!

**Comment by giorov** [comment] 2022-03-12 21:34
Alright yeah that was a shot in the dark, yeah.
