### ISSUE TITLE
Crash after a few minutes of being connected to a server

### ISSUE THREAD

**Issue by elliots2007** [Johni0702/bobby#13] opened 2021-03-12 17:35 UTC
Maybe related to #10. My game crashes with bobby with this error message:

The game crashed whilst unexpected error
Error: java.lang.ArrayIndexOutOfBoundsException: Index -1 out of bounds for length 257
Exit Code: -1

and here is the latest log:
[latest.log](https://github.com/Johni0702/bobby/files/6131868/latest.log)

it also happens without any mods.

**Comment by Johni0702** [comment] 2021-03-12 23:43
Could you send a log of when it crashed without any other mods? The one you sent has lithium right in the crash which makes it more difficult to analyze than necessary.

**Comment by elliots2007** [comment] 2021-03-13 13:23
Hmm, can't seem to get it crashing

**Comment by Johni0702** [comment] 2021-03-15 09:58
Closing under the assumption that this is caused by the same bug as #10.
If you are still running into this with Bobby 1.1.0, please re-open the issue.

**Closed by Johni0702** 2021-03-15 09:58 UTC
