### ISSUE TITLE
Bobby for 1.20

### ISSUE THREAD

**Issue by itsAK14** [Johni0702/bobby#255] opened 2024-02-25 10:15 UTC
i really want to use this mod but it has no support for mc version 1.20

**Comment by MaledictYtb** [comment] 2024-03-03 20:34
Yes it does 
https://modrinth.com/mod/bobby/versions

**Comment by UnforseenDeath** [comment] 2024-03-24 07:32
> Yes it does https://modrinth.com/mod/bobby/versions

he meant 1.20 not 1.20.1 or above.

**Comment by Johni0702** [comment] 2024-05-05 12:33
Duplicate of #191

**Closed by Johni0702** 2024-05-05 12:33 UTC
